### ISSUE TITLE
只能解析小的数据包吗

### ISSUE THREAD

**Issue by iWorkers** [nmsdss/douyin_live_protobuf#1]
大的数据包解析就出错

**Comment by nmsdss** [comment]
麻烦把数据包发我看下

**Comment by iWorkers** [comment]
2kb以上的包你自己抓下解析看下

**Comment by nmsdss** [comment]
我这边没问题，麻烦你把报错信息和数据包发下吧
![image](https://user-images.githubusercontent.com/95068495/192135114-94f8aa2e-1895-467e-b177-99cabe90dc65.png)
![image](https://user-images.githubusercontent.com/95068495/192135141-0302a3b1-6106-4914-abc2-e6cd3be86dcc.png)

**Comment by iWorkers** [comment]
![1664149925(1)](https://user-images.githubusercontent.com/75261857/192171414-566637a7-799f-45ad-8dc2-de2d026c3c7c.png)
是我环境配置问题吗，帮我看下

![1664150328(1)](https://user-images.githubusercontent.com/75261857/192171580-2e180a23-62c2-4bc3-8e54-796eb38da372.png)

**Comment by nmsdss** [comment]
![image](https://user-images.githubusercontent.com/95068495/192175930-9892c05a-0afa-48bd-a8d7-0da2ff8e75c9.png)
可能是因为pyexecjs这个包的编码问题
